#!/bin/bash

# This accepts only user actions belonging to My web application
#docker run --name dynatracevisitflow -p 8080:8080 dynatracevisitflow -application "My web application"

# This accepts user actions from all applications
docker run --name dynatracevisitflow -p 8080:8080 dynatracevisitflow
